name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    # 指定运行器环境
    runs-on: ubuntu-latest
    # 设置 node 版本
    strategy:
      matrix:
        node-version: [18]

    steps:
    - name: 拉取仓库代码
      uses: actions/checkout@v2

    - name: 设置node环境
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}

    - name: 设置淘宝镜像
      run: yarn config set registry https://registry.npmmirror.com

    - name: 安装依赖
      run: yarn install

    - name: lint检查
      run: npm run lint

    - name: jest测试
      run: npm test

    - name: 打包
      run: npm run build

    # - name: 生成docs文档
    #   run: npm run docs
  
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: pm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    # - name: 部署
    #   uses: JamesIves/github-pages-deploy-action@releases/v3
    #   with: 
    #     # 在第三步中设置的 ACCESS_TOKEN 
    #     ACCESS_TOKEN: ${{ secrets.MYTOKEN }}
    #     # 指定推送到的远程分支
    #     BRANCH: pages
    #     # 指定构建之后的产出路径
    #     FOLDER: build
    # - run: npm publish --access public
    #   env:
    #     # 设置NPM_TOKEN
    #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
